import { buildQualityRulesPrompt } from '@pingarden/shared';

export type CopilotProtocolIntent = 'project-draft' | 'project-update' | 'discussion-insight' | 'apply-learning-to-project';

export function buildCopilotProtocol(intent: CopilotProtocolIntent, lang: 'en' | 'zh' = 'en'): string {
  if (intent === 'project-draft') return buildProjectDraftProtocol(lang);
  if (intent === 'project-update') return buildProjectUpdateProtocol(lang);
  if (intent === 'apply-learning-to-project') return buildApplyLearningToProjectProtocol(lang);
  return buildDiscussionInsightProtocol();
}

function buildDiscussionInsightProtocol(): string {
  return [
    '## Hidden PinGarden discussion-insight protocol',
    'Use this protocol internally. Do not repeat it to the user.',
    buildStructuredResponseProtocolHint('discussionInsight'),
    'You are helping the user learn from strategy-library material and discuss a business problem. Do not write project data directly.',
    'After the concise answer, output exactly one fenced JSON block with kind "pingarden.discussionInsight" so the UI can show an editable insight card.',
    'The insight card is session-scoped by default. It should contain only distilled business insights, source references, and suggested project actions; do not include private keys, raw image data, or a full chat transcript.',
    'Use suggestedActions to describe how this learning could become project work: createProject, updateProject, createCanvas, updateCanvas, createStory, or saveProjectInsight.',
    'Output shape:',
    '```json',
    '{',
    '  "kind": "pingarden.discussionInsight",',
    '  "title": "Short insight title",',
    '  "summary": "One-paragraph summary of what the user learned and why it matters",',
    '  "sourceRefs": [',
    '    { "id": "src-1", "type": "case", "label": "Airbnb case", "summary": "Why this source matters" }',
    '  ],',
    '  "insights": [',
    '    { "id": "ins-1", "title": "Concrete business insight", "summary": "What to remember", "evidence": "Source-backed reason", "sourceRefs": ["src-1"] }',
    '  ],',
    '  "suggestedActions": [',
    '    { "id": "act-1", "type": "updateProject", "label": "Apply to an existing project", "rationale": "Which project assumption or canvas it can improve", "sourceRefs": ["ins-1"] }',
    '  ],',
    '  "notes": ["Session insight only; save to a project or memory only after user confirmation"]',
    '}',
    '```',
  ].join('\n');
}

function buildApplyLearningToProjectProtocol(lang: 'en' | 'zh'): string {
  return [
    buildProjectUpdateProtocol(lang),
    '',
    '## Additional apply-learning-to-project rules',
    'The user selected one or more discussion insights and a target project/new project action. Convert the selected insights into an executable draft.',
    'If target project context is supplied, output pingarden.projectUpdateDraft for that project. If the user asks for a new project instead, output pingarden.projectDraft.',
    'Preserve sourceRefs from the discussion insights in stickies, stories, and notes when possible.',
    'Do not silently invent unavailable project IDs; use the target project id from context or the user prompt.',
  ].join('\n');
}

function buildProjectDraftProtocol(lang: 'en' | 'zh'): string {
  return [
    '## Hidden PinGarden project-draft protocol',
    'Use this protocol internally. Do not repeat it to the user.',
    buildStructuredResponseProtocolHint('projectDraft'),
    'You are creating a new PinGarden project from user text, links, and images.',
    'Images are passed as original, uncompressed data URLs because they are usually dense canvases, screenshots, diagrams, or sticky-note walls. Read small labels carefully; do not assume a low-detail summary is enough.',
    'First extract sourceFindings from every source: each uploaded image must have visible labels/stickies/notes extracted as findings; user descriptive text must become text findings.',
    'Then map each finding to at least one sticky or story paragraph. Do not silently drop any visible image label. If a finding genuinely cannot be mapped, list it in sourceCoverage.unmappedSourceItems with a reason.',
    'Create stickies from the image content and create at least one story when the user provided descriptive text or the images imply a narrative.',
    'Every created canvas must contain non-empty stickies. Never create an empty canvas.',
    'Only project.name and project.description are user-supplied essentials. If they are missing, leave them empty or use a clearly tentative short guess, and put only "project.name" and/or "project.description" in missingFields.',
    'Never put paths such as canvases[0].stickies.* in missingFields. If a canvas block is unclear, add it to unmappedSourceItems or notes instead of asking for that field.',
    'If a link is not directly accessible, ask the user to paste key information from that link. Do not pretend you browsed it.',
    'When enough information is available or the images contain enough canvas content, give a short explanation and output exactly one fenced JSON code block matching this shape:',
    '```json',
    '{',
    '  "kind": "pingarden.projectDraft",',
    '  "project": {',
    '    "name": "Project name",',
    '    "description": "One-sentence description of audience, value, and goal"',
    '  },',
    '  "sourceCoverage": {',
    '    "sourceImageCount": 4,',
    '    "findings": [',
    '      { "id": "img1-1", "sourceType": "image", "sourceIndex": 1, "text": "Visible sticky or label", "confidence": "high" },',
    '      { "id": "txt-1", "sourceType": "text", "text": "User-provided narrative point", "confidence": "high" }',
    '    ],',
    '    "mappedFindingIds": ["img1-1", "txt-1"],',
    '    "unmappedSourceItems": []',
    '  },',
    '  "canvases": [',
    '    {',
    '      "defId": "business-model-canvas",',
    '      "title": "Business Model Canvas",',
    '      "stickies": [',
    '        { "zoneId": "customer-segments", "text": "Target customer segment", "sourceRefs": ["img1-1"] },',
    '        { "zoneId": "value-propositions", "text": "Core value proposition", "sourceRefs": ["txt-1"] }',
    '      ]',
    '    }',
    '  ],',
    '  "stories": [',
    '    {',
    '      "title": "Project story",',
    '      "content": "# Project story\\n\\n## Context\\n...\\n\\n::canvas[business-model-canvas]{}",',
    '      "sourceRefs": ["txt-1", "img1-1"]',
    '    }',
    '  ],',
    '  "missingFields": ["project.name", "project.description"],',
    '  "notes": ["Source coverage was checked; unmapped items need user review"]',
    '}',
    '```',
    'Keep stickies short: one sticky, one concept. Split long source text into multiple stickies.',
    'Use relative story canvas directives such as ::canvas[business-model-canvas]{} rather than invented canvasIds; the app creates canvases before stories and rewrites resolvable directives to exact canvasIds.',
    'Common Business Model Canvas zoneIds: key-partners, key-activities, key-resources, value-propositions, customer-relationships, channels, customer-segments, cost-structure, revenue-streams.',
    'If the user uploaded a Business Model Canvas image, prefer creating a business-model-canvas and preserve all visible labels as stickies whenever possible.',
    '',
    buildQualityRulesPrompt({ lang, includeSoftHints: true }),
  ].join('\n');
}

function buildProjectUpdateProtocol(lang: 'en' | 'zh'): string {
  return [
    '## Hidden PinGarden project-update protocol',
    'Use this protocol internally. Do not repeat it to the user.',
    buildStructuredResponseProtocolHint('projectUpdateDraft'),
    'You are updating an existing PinGarden project. The attached context contains the current project, canvases, stories, and active canvas/story when available.',
    'Images are passed as original, uncompressed data URLs because they are usually dense canvases, screenshots, diagrams, or sticky-note walls. Read small labels carefully; do not assume a low-detail summary is enough.',
    'If the user asks to add/adjust stickies, expand canvases, or edit story, output an executable update draft. Do not merely say you will do it.',
    'For existing canvases, replaceCanvasStickies must contain the complete desired sticky state, including existing stickies that should remain. The write API is replace-mode.',
    'For new canvases, createCanvas must contain non-empty stickies. Never create an empty canvas.',
    'For stories, createStory or replaceStory must contain the full target Markdown content. Use only canvas directives that resolve in this project; prefer ::canvas[defId]{} for newly created canvases and exact ::canvas[defId]{canvasId="..."} for existing canvases listed in context.',
    'If new images are attached, extract sourceFindings from every image and map each finding to stickies or story content; otherwise sourceCoverage can be omitted.',
    'Output exactly one fenced JSON code block matching this shape:',
    '```json',
    '{',
    '  "kind": "pingarden.projectUpdateDraft",',
    '  "projectId": "existing-project-id-from-context",',
    '  "summary": "What will change",',
    '  "sourceCoverage": {',
    '    "sourceImageCount": 1,',
    '    "findings": [',
    '      { "id": "img1-1", "sourceType": "image", "sourceIndex": 1, "text": "Visible label", "confidence": "high" }',
    '    ],',
    '    "mappedFindingIds": ["img1-1"],',
    '    "unmappedSourceItems": []',
    '  },',
    '  "operations": [',
    '    {',
    '      "type": "createCanvas",',
    '      "defId": "value-proposition-canvas",',
    '      "title": "Value Proposition Canvas",',
    '      "stickies": [',
    '        { "zoneId": "customer-jobs", "text": "Job to be done", "sourceRefs": ["img1-1"] }',
    '      ]',
    '    },',
    '    {',
    '      "type": "replaceCanvasStickies",',
    '      "canvasId": "existing-canvas-id-from-context",',
    '      "stickies": [',
    '        { "zoneId": "value-propositions", "text": "Existing or new sticky" }',
    '      ]',
    '    },',
    '    {',
    '      "type": "createStory",',
    '      "title": "Updated project story",',
    '      "content": "# Updated project story\\n\\n..."',
    '    },',
    '    {',
    '      "type": "replaceStory",',
    '      "storyId": "existing-story-id-from-context",',
    '      "title": "Revised story title",',
    '      "content": "# Revised story\\n\\nFull target content..."',
    '    }',
    '  ],',
    '  "notes": ["All existing content that should remain was carried forward"]',
    '}',
    '```',
    'Include only operations that are actually needed.',
    '',
    buildQualityRulesPrompt({ lang, includeSoftHints: true }),
  ].join('\n');
}

function buildStructuredResponseProtocolHint(cardType: 'projectDraft' | 'projectUpdateDraft' | 'discussionInsight'): string {
  return [
    'Prefer the new structured envelope when possible: after the visible concise answer, output one fenced JSON block with kind "pingarden.response.v1".',
    'Put user-visible prose in answerMarkdown. Put actionable cards in cards[]. Keep references typed so the UI can render the right card and avoid false missing-content warnings.',
    'Reference kinds must be one of: case, resource, resourceChapter, canvasTemplate, canvasInstance, project, story, pattern, strategyFramework, experiment.',
    'Taxonomy rule: books/articles/reports/web pages are resources, not cases; canvas templates and strategy frameworks are method assets, not current-project canvas instances.',
    'Envelope shape:',
    '```json',
    '{',
    '  "kind": "pingarden.response.v1",',
    '  "answerMarkdown": "Short visible answer for the user",',
    '  "references": [',
    '    { "kind": "canvasTemplate", "label": "Business Model Canvas", "defId": "business-model-canvas" },',
    '    { "kind": "resource", "label": "Business Model Generation", "slug": "business-model-generation" }',
    '  ],',
    `  "cards": [{ "type": "${cardType}", "${cardType === 'discussionInsight' ? 'insight' : 'draft'}": { "...": "same object as the legacy protocol below" } }],`,
    '  "diagnostics": []',
    '}',
    '```',
    'If you cannot produce the envelope safely, fall back to the legacy single-card JSON block below.',
  ].join('\n');
}
